default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: exam_app_development
test:
  <<: *default
  database: exam_app_test

production:
  <<: *default
  database: exam_app_production
  username: exam_app
  password: <%= ENV['EXAM_APP_DATABASE_PASSWORD'] %>
